#!/usr/bin/env python3
"""
Microsoft Tag / HCCB 5x10 reverse-engineered encoder/offline decoder (v4).

Reverse-engineered from Microsoft Tag Reader 5.6.4 (Android):
  raw payload: CRC16-X25 (LE16) + prefix (LE16) + code (LE32)
  RS: GF(32), primitive x^5+x^2+1, t=2, parity-first; native ARM parity packing reproduced
  whitening: XOR fixed 100-byte table (first 11 bytes used for 5x10 tags)
  4-colour packing: 2 source bits per colour index, source bits read LSB-first
  final 50 cells: 44 encoded cells + filler [0,1] + calibration [0,1,2,3]

This script can:
  encode PREFIX CODE [--svg out.svg] [--png out.png] [--tag out.tag]
  decode-symbols 50 comma/space-separated colour indices
  decode-tag file.tag
  decode-png image.png   (clean images generated by this script)

Palette index convention used here (matching Microsoft Tag print palette):
  0 = yellow, 1 = magenta, 2 = black, 3 = cyan

The PNG decoder is deliberately a clean-image decoder, not yet a camera/photo detector.
"""

from __future__ import annotations
import argparse
import itertools
import math
import random
import re
import struct
import sys
from pathlib import Path

# 100-byte XOR table embedded in libtagdecoder.so.
XOR_TABLE = bytes.fromhex(
    "0f4d9417483a861c02f8e3e896e8074c"
    "d1f7183b18cfc97723630430fdc82fcb"
    "2104c488055a43d3e2886a8a70d19be6"
    "996910475f80830624b253fd6478905a"
    "6250c64a49df7d2c9b08860c7a612b6a"
    "a5d107123046ce404b7786ea2bcb42fe"
    "8a8a3dc1"
)

# 4-colour print palette. The symbol-numbering convention follows the
# calibration sequence stored by the decoder/encoder: [0,1,2,3].
PALETTE = {
    0: (255, 255,   0),  # yellow
    1: (255,   0, 255),  # magenta
    2: (  0,   0,   0),  # black
    3: (  0, 255, 255),  # cyan
}
PALETTE_HEX = {k: '#%02X%02X%02X' % v for k, v in PALETTE.items()}

# GF(2^5) / Reed-Solomon parameters from CReedSolomon2::Initialize(5, 2).
GF_M = 5
GF_N = (1 << GF_M) - 1       # 31
GF_PRIMITIVE = 0x25          # x^5 + x^2 + 1
RS_T = 2
RS_PARITY_SYMBOLS = 2 * RS_T # 4 x 5-bit symbols
RS_DATA_CAPACITY = GF_N - RS_PARITY_SYMBOLS  # 27 symbols


def _gf_tables():
    alpha = [0] * GF_N
    index = [GF_N] * (1 << GF_M)  # 31 is zero sentinel
    alpha[0] = 1
    for i in range(1, GF_N):
        x = alpha[i - 1] << 1
        if x & (1 << GF_M):
            x ^= GF_PRIMITIVE
        alpha[i] = x & GF_N
    for i, v in enumerate(alpha):
        index[v] = i
    index[0] = GF_N
    return alpha, index

GF_ALPHA, GF_INDEX = _gf_tables()


def _poly_mul_gf(a, b):
    out = [0] * (len(a) + len(b) - 1)
    for i, av in enumerate(a):
        for j, bv in enumerate(b):
            if av and bv:
                out[i+j] ^= GF_ALPHA[(GF_INDEX[av] + GF_INDEX[bv]) % GF_N]
    return out


def _generator_poly_values():
    # Product (x + a^1)(x + a^2)(x + a^3)(x + a^4), low coefficient first.
    p = [1]
    for root_power in range(1, RS_PARITY_SYMBOLS + 1):
        p = _poly_mul_gf(p, [GF_ALPHA[root_power], 1])
    return p

RS_GENERATOR_VALUES = _generator_poly_values()           # [17,9,6,30,1]
RS_GENERATOR_LOGS = [GF_INDEX[x] for x in RS_GENERATOR_VALUES]


def crc16_x25(data: bytes) -> int:
    """CRC-16/IBM-SDLC (aka X-25), reflected poly 0x8408, init/xorout FFFF."""
    crc = 0xFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ (0x8408 if (crc & 1) else 0)
    return crc ^ 0xFFFF


def bytes_to_5bit_symbols(data: bytes) -> list[int]:
    """MSB-first bitstream, split into 5-bit symbols; right-pad final symbol with zero."""
    symbols = []
    acc = 0
    bits = 0
    for b in data:
        acc = (acc << 8) | b
        bits += 8
        while bits >= 5:
            bits -= 5
            symbols.append((acc >> bits) & 0x1F)
            acc &= (1 << bits) - 1 if bits else 0
    if bits:
        symbols.append((acc << (5 - bits)) & 0x1F)
    return symbols


def pack_5bit_symbols_native(symbols: list[int]) -> bytes:
    """Pack GF(32) symbols exactly as the Microsoft Tag encoder emits them.

    Symbols are concatenated MSB-first in 5-bit units; the last output byte is
    padded with zero bits on the right.  Real-world Microsoft Tag samples were
    used to correct an earlier reverse-engineering mistake that put the final
    partial symbol in the low nibble.
    """
    acc = 0
    bits = 0
    out = bytearray()
    for sym in symbols:
        if not (0 <= sym < (1 << GF_M)):
            raise ValueError('5-bit symbol out of range')
        acc = (acc << GF_M) | sym
        bits += GF_M
        while bits >= 8:
            bits -= 8
            out.append((acc >> bits) & 0xFF)
            acc &= (1 << bits) - 1 if bits else 0
    if bits:
        out.append((acc << (8 - bits)) & 0xFF)
    return bytes(out)

def split_5bit_symbols_native(data: bytes) -> list[int]:
    """Port of APK SplitMessageIntoSymbols<unsigned char> for m=5."""
    m = GF_M
    out: list[int] = []
    cur = 0
    remaining_symbol_bits = m
    for byte0 in data:
        work = byte0
        remaining_byte_bits = 8
        while remaining_byte_bits > 0:
            take = min(remaining_symbol_bits, remaining_byte_bits)
            piece = work >> (8 - take)
            work = (work << take) & 0xFF
            cur = ((cur << take) & 0xFF) | piece
            remaining_symbol_bits -= take
            remaining_byte_bits -= take
            if remaining_symbol_bits == 0:
                out.append(cur)
                cur = 0
                remaining_symbol_bits = m
    if remaining_symbol_bits < m:
        out.append((cur << remaining_symbol_bits) & 0xFF)
    return out


def rs_parity_for_raw8(raw8: bytes) -> tuple[list[int], bytes]:
    if len(raw8) != 8:
        raise ValueError('Microsoft Tag 5x10 raw block must be 8 bytes')
    data_symbols = bytes_to_5bit_symbols(raw8)
    # 64 bits -> 13 GF(32) symbols. Native encoder logically shortens a (31,27) code
    # by prepending zero data symbols, then feeds positions 26..0 in descending order.
    if len(data_symbols) > RS_DATA_CAPACITY:
        raise ValueError('too many RS data symbols')
    parity = [0] * RS_PARITY_SYMBOLS
    genlog = RS_GENERATOR_LOGS  # five coefficients; encoder uses entries 0..3
    for i in range(RS_DATA_CAPACITY - 1, -1, -1):
        datum = data_symbols[i] if i < len(data_symbols) else 0
        feedback_value = datum ^ parity[RS_PARITY_SYMBOLS - 1]
        feedback = GF_INDEX[feedback_value]
        if feedback != GF_N:
            for j in range(RS_PARITY_SYMBOLS - 1, 0, -1):
                if genlog[j] != GF_N:
                    parity[j] = parity[j - 1] ^ GF_ALPHA[(feedback + genlog[j]) % GF_N]
                else:
                    parity[j] = parity[j - 1]
            parity[0] = GF_ALPHA[(feedback + genlog[0]) % GF_N]
        else:
            for j in range(RS_PARITY_SYMBOLS - 1, 0, -1):
                parity[j] = parity[j - 1]
            parity[0] = 0
    return parity, pack_5bit_symbols_native(parity)


def build_raw8(prefix: int, code: int) -> bytes:
    if not (0 <= prefix <= 0xFFFF):
        raise ValueError('prefix must fit 16 bits (0..65535)')
    if not (0 <= code <= 0xFFFFFFFF):
        raise ValueError('5x10 Microsoft Tag code must fit 32 bits (0..4294967295)')
    body = struct.pack('<HI', prefix, code)
    crc = crc16_x25(body)
    return struct.pack('<H', crc) + body


def whiten(data: bytes) -> bytes:
    return bytes(b ^ XOR_TABLE[i % len(XOR_TABLE)] for i, b in enumerate(data))


def bytes_to_color_symbols(data: bytes) -> list[int]:
    """Native 4-colour bit packing: LSB-first source bits, two bits -> symbol."""
    out = []
    total_bits = len(data) * 8
    if total_bits % 2:
        raise ValueError('data bit count must be even')
    for pos in range(0, total_bits, 2):
        b0 = (data[pos // 8] >> (pos % 8)) & 1
        p1 = pos + 1
        b1 = (data[p1 // 8] >> (p1 % 8)) & 1
        out.append((b0 << 1) | b1)
    return out


def color_symbols_to_bytes(symbols: list[int]) -> bytes:
    out = bytearray((len(symbols) * 2 + 7) // 8)
    bitpos = 0
    for s in symbols:
        if not (0 <= s <= 3):
            raise ValueError(f'colour symbol out of range: {s}')
        for bit in ((s >> 1) & 1, s & 1):
            if bit:
                out[bitpos // 8] |= 1 << (bitpos % 8)
            bitpos += 1
    return bytes(out)


def encode_symbols(prefix: int, code: int) -> dict:
    raw8 = build_raw8(prefix, code)
    parity_syms, parity_bytes = rs_parity_for_raw8(raw8)
    if len(parity_bytes) != 3:
        raise AssertionError(f'unexpected packed parity length: {len(parity_bytes)}')
    rsbuf = parity_bytes + raw8
    if len(rsbuf) != 11:
        raise AssertionError('unexpected RS buffer length')
    xored = whiten(rsbuf)
    data_cells = bytes_to_color_symbols(xored)
    if len(data_cells) != 44:
        raise AssertionError('unexpected data cell count')
    cells = data_cells + [0, 1] + [0, 1, 2, 3]
    return {
        'prefix': prefix,
        'code': code,
        'tid': f'{prefix:05d}_{code:010d}',
        'crc16': int.from_bytes(raw8[:2], 'little'),
        'raw8': raw8,
        'data_symbols_5bit': bytes_to_5bit_symbols(raw8),
        'rs_parity_symbols': parity_syms,
        'rs_parity_bytes': parity_bytes,
        'rs_parity_symbols_as_native_decoder_sees_them': split_5bit_symbols_native(parity_bytes)[:4],
        'rs_buffer': rsbuf,
        'xored': xored,
        'cells': cells,
    }


def decode_symbols(cells: list[int], verify_crc: bool = True) -> dict:
    if len(cells) != 50:
        raise ValueError(f'expected exactly 50 colour cells, got {len(cells)}')
    if any(c not in (0, 1, 2, 3) for c in cells):
        raise ValueError('colour cells must be integers 0..3')
    # Last four are fixed colour calibration, two immediately before them are filler.
    calibration = cells[46:50]
    filler = cells[44:46]
    xored = color_symbols_to_bytes(cells[:44])
    if len(xored) != 11:
        raise AssertionError('unexpected inverse packed size')
    rsbuf = whiten(xored)
    parity_bytes = rsbuf[:3]
    raw8 = rsbuf[3:11]
    stored_crc = int.from_bytes(raw8[:2], 'little')
    body = raw8[2:]
    calc_crc = crc16_x25(body)
    crc_ok = stored_crc == calc_crc
    if verify_crc and not crc_ok:
        raise ValueError(f'CRC mismatch: stored 0x{stored_crc:04X}, calculated 0x{calc_crc:04X}; image/symbols likely contain errors')
    prefix, code = struct.unpack('<HI', body)
    expected = encode_symbols(prefix, code)
    return {
        'prefix': prefix,
        'code': code,
        'tid': f'{prefix:05d}_{code:010d}',
        'stored_crc16': stored_crc,
        'calculated_crc16': calc_crc,
        'crc_ok': crc_ok,
        'raw8': raw8,
        'rs_parity_bytes': parity_bytes,
        'rs_parity_matches_reencode': parity_bytes == expected['rs_parity_bytes'],
        'filler': filler,
        'calibration': calibration,
        'filler_ok': filler == [0, 1],
        'calibration_ok': calibration == [0, 1, 2, 3],
    }


def _is_strong_decode(d: dict) -> bool:
    # CRC + the six fixed trailer cells are independent checks and are strong
    # enough for camera orientation selection.  Do not require a parity
    # re-encode match here: some published/edited Microsoft Tag artwork has
    # damaged parity cells while preserving an intact payload and CRC.
    return bool(d.get('crc_ok') and d.get('filler_ok') and d.get('calibration_ok'))


def decode_symbols_resilient(cells: list[int], max_cell_errors: int = 2) -> dict:
    """Decode symbols and brute-correct a few misclassified 2-bit colour cells.

    This is not a replacement for the native GF(32) Reed-Solomon decoder. It is a
    practical image-decoding safety net: try small colour substitutions and use the
    independent CRC + re-encoded RS parity as a very strong validity check.
    """
    if len(cells) != 50:
        raise ValueError(f'expected exactly 50 colour cells, got {len(cells)}')
    base = list(cells)
    d = decode_symbols(base, verify_crc=False)
    if _is_strong_decode(d):
        d['corrected_cells'] = []
        return d
    if max_cell_errors <= 0:
        raise ValueError('symbol block failed CRC/RS validation')

    # Only the first 44 cells carry encoded data. Filler/calibration do not affect ID.
    positions = range(44)
    for pos in positions:
        original = base[pos]
        for alt in range(4):
            if alt == original:
                continue
            trial = base.copy()
            trial[pos] = alt
            r = decode_symbols(trial, verify_crc=False)
            if _is_strong_decode(r):
                r['corrected_cells'] = [(pos, original, alt)]
                return r
    if max_cell_errors <= 1:
        raise ValueError('symbol block failed CRC/RS validation after 1-cell correction')

    for p1, p2 in itertools.combinations(positions, 2):
        o1, o2 = base[p1], base[p2]
        for a1 in range(4):
            if a1 == o1:
                continue
            for a2 in range(4):
                if a2 == o2:
                    continue
                trial = base.copy()
                trial[p1] = a1
                trial[p2] = a2
                r = decode_symbols(trial, verify_crc=False)
                if _is_strong_decode(r):
                    r['corrected_cells'] = [(p1, o1, a1), (p2, o2, a2)]
                    return r
    raise ValueError('symbol block failed CRC/RS validation after 2-cell correction')


# --- simple renderer for clean digital tags ---
DEFAULT_GEOM = {
    'tri_h': 60.0,
    'separator': 11.0,
    'outer_white': 26.0,
    'black_side': 24.0,
    'black_top': 18.0,
    'black_bottom': 34.0,
}


def _geometry(scale=1.0):
    g = {k: v * scale for k, v in DEFAULT_GEOM.items()}
    h = g['tri_h']
    base = 2 * h / math.sqrt(3)
    dx = base / 2
    lattice_w = base + 9 * dx
    black_w = g['black_side'] * 2 + lattice_w
    black_h = g['black_top'] + g['black_bottom'] + 5 * h + 6 * g['separator']
    width = black_w + 2 * g['outer_white']
    height = black_h + 2 * g['outer_white']
    x_black = g['outer_white']
    y_black = g['outer_white']
    x0 = x_black + g['black_side']
    y_sep0 = y_black + g['black_top']
    return g, base, dx, lattice_w, width, height, x_black, y_black, x0, y_sep0


def _triangle_points(row: int, col: int, scale=1.0):
    g, base, dx, _, _, _, _, _, x0, y_sep0 = _geometry(scale)
    top = y_sep0 + row * (g['separator'] + g['tri_h']) + g['separator']
    bottom = top + g['tri_h']
    x = x0 + col * dx
    if col % 2 == 0:  # downward-pointing
        pts = [(x, top), (x + base, top), (x + base / 2, bottom)]
    else:             # upward-pointing
        pts = [(x, bottom), (x + base, bottom), (x + base / 2, top)]
    return pts


def _triangle_centroid(row: int, col: int, scale=1.0):
    pts = _triangle_points(row, col, scale)
    return (sum(p[0] for p in pts)/3.0, sum(p[1] for p in pts)/3.0)


def render_svg(cells: list[int], path: str | Path, scale=1.0):
    if len(cells) != 50:
        raise ValueError('need 50 cells')
    g, _, _, _, width, height, x_black, y_black, _, y_sep0 = _geometry(scale)
    black_w = width - 2 * g['outer_white']
    black_h = height - 2 * g['outer_white']
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.3f} {height:.3f}" width="{width:.0f}" height="{height:.0f}">',
        '<rect width="100%" height="100%" fill="#FFFFFF"/>',
        f'<rect x="{x_black:.3f}" y="{y_black:.3f}" width="{black_w:.3f}" height="{black_h:.3f}" fill="#000000"/>',
    ]
    # Horizontal registration/separator bars.
    for r in range(6):
        y = y_sep0 + r * (g['separator'] + g['tri_h'])
        lines.append(f'<rect x="{x_black:.3f}" y="{y:.3f}" width="{black_w:.3f}" height="{g["separator"]:.3f}" fill="#FFFFFF"/>')
    for idx, symbol in enumerate(cells):
        row, col = divmod(idx, 10)
        pts = _triangle_points(row, col, scale)
        ptxt = ' '.join(f'{x:.3f},{y:.3f}' for x, y in pts)
        lines.append(f'<polygon data-cell="{idx}" data-symbol="{symbol}" points="{ptxt}" fill="{PALETTE_HEX[symbol]}"/>')
    lines.append('</svg>')
    Path(path).write_text('\n'.join(lines), encoding='utf-8')


def render_png(cells: list[int], path: str | Path, scale=2.0):
    try:
        from PIL import Image, ImageDraw
    except ImportError as e:
        raise RuntimeError('Pillow is required for PNG output; use --svg if unavailable') from e
    g, _, _, _, width, height, x_black, y_black, _, y_sep0 = _geometry(scale)
    W, H = int(math.ceil(width)), int(math.ceil(height))
    img = Image.new('RGB', (W, H), (255,255,255))
    dr = ImageDraw.Draw(img)
    black_w = width - 2 * g['outer_white']
    black_h = height - 2 * g['outer_white']
    dr.rectangle([x_black, y_black, x_black+black_w, y_black+black_h], fill=(0,0,0))
    for r in range(6):
        y = y_sep0 + r * (g['separator'] + g['tri_h'])
        dr.rectangle([x_black, y, x_black+black_w, y+g['separator']], fill=(255,255,255))
    for idx, symbol in enumerate(cells):
        row, col = divmod(idx, 10)
        pts = _triangle_points(row, col, scale)
        dr.polygon(pts, fill=PALETTE[symbol])
    img.save(path)


def decode_clean_png(path: str | Path, scale: float | None = None) -> dict:
    """Decode a clean PNG produced by render_png. No perspective/photo detection."""
    try:
        from PIL import Image
    except ImportError as e:
        raise RuntimeError('Pillow is required for PNG input') from e
    img = Image.open(path).convert('RGB')
    # Infer uniform renderer scale from width if omitted.
    if scale is None:
        _, _, _, _, base_w, _, *_ = _geometry(1.0)
        scale = img.width / base_w
    cells = []
    for idx in range(50):
        row, col = divmod(idx, 10)
        x, y = _triangle_centroid(row, col, scale)
        rgb = img.getpixel((min(img.width-1, max(0, round(x))), min(img.height-1, max(0, round(y)))))
        symbol = min(PALETTE, key=lambda k: sum((rgb[i] - PALETTE[k][i])**2 for i in range(3)))
        cells.append(symbol)
    result = decode_symbols(cells)
    result['cells'] = cells
    return result


def _order_quad_clockwise(pts):
    import numpy as np
    pts = np.asarray(pts, dtype=np.float32).reshape(4, 2)
    c = pts.mean(axis=0)
    ang = np.arctan2(pts[:, 1] - c[1], pts[:, 0] - c[0])
    pts = pts[np.argsort(ang)]
    start = int(np.argmin(pts[:, 0] + pts[:, 1]))
    return np.roll(pts, -start, axis=0)


def _find_tag_quad_bgr(img):
    """Find an approximate outer black HCCB rectangle in a photo/crop."""
    import cv2
    import numpy as np

    h, w = img.shape[:2]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    mask = (gray < 95).astype(np.uint8) * 255
    # Use an orientation-invariant closing kernel: after a 90° rotation the white
    # row separators become vertical, so a strongly anisotropic kernel would fail.
    k = max(3, int(round(min(h, w) * 0.025))) | 1
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (k, k))
    joined = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    joined = cv2.morphologyEx(joined, cv2.MORPH_OPEN,
                              cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3)))
    contours, _ = cv2.findContours(joined, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours = sorted(contours, key=cv2.contourArea, reverse=True)
    min_area = h * w * 0.03
    for cnt in contours[:20]:
        if cv2.contourArea(cnt) < min_area:
            continue
        hull = cv2.convexHull(cnt)
        peri = cv2.arcLength(hull, True)
        for epsf in (0.015, 0.025, 0.04, 0.06, 0.09):
            approx = cv2.approxPolyDP(hull, epsf * peri, True)
            if len(approx) == 4 and cv2.isContourConvex(approx):
                return _order_quad_clockwise(approx.reshape(4, 2)), joined
        rect = cv2.minAreaRect(hull)
        box = cv2.boxPoints(rect)
        return _order_quad_clockwise(box), joined
    raise ValueError('could not locate a Microsoft Tag black frame; try a tighter crop')


def _sample_patch_rgb(img_bgr, x, y, radius):
    import cv2
    import numpy as np
    h, w = img_bgr.shape[:2]
    x0, x1 = max(0, int(round(x-radius))), min(w, int(round(x+radius+1)))
    y0, y1 = max(0, int(round(y-radius))), min(h, int(round(y+radius+1)))
    patch = img_bgr[y0:y1, x0:x1]
    if patch.size == 0:
        raise ValueError('sample point outside warped tag')
    rgb = cv2.cvtColor(patch, cv2.COLOR_BGR2RGB).reshape(-1, 3)
    return np.median(rgb, axis=0).astype(float)


def decode_photo(path: str | Path, max_cell_errors: int = 2,
                 debug_warp: str | Path | None = None) -> dict:
    """Decode a photographed/cropped 5x10 Microsoft Tag using OpenCV."""
    try:
        import cv2
        import numpy as np
    except ImportError as e:
        raise RuntimeError('OpenCV (cv2) and numpy are required for photo decoding') from e

    img = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if img is None:
        raise ValueError(f'cannot read image: {path}')
    max_dim = max(img.shape[:2])
    if max_dim > 2200:
        s = 2200.0 / max_dim
        img = cv2.resize(img, None, fx=s, fy=s, interpolation=cv2.INTER_AREA)

    quad, _ = _find_tag_quad_bgr(img)
    g, _, _, _, full_w, full_h, _, _, _, _ = _geometry(2.0)
    black_w = int(round(full_w - 2 * g['outer_white']))
    black_h = int(round(full_h - 2 * g['outer_white']))
    dst = np.array([[0, 0], [black_w-1, 0], [black_w-1, black_h-1], [0, black_h-1]], dtype=np.float32)

    mappings = []
    q = np.asarray(quad, dtype=np.float32)
    for rev in (False, True):
        qq = q if not rev else q[[0, 3, 2, 1]]
        for shift in range(4):
            mappings.append((rev, shift, np.roll(qq, -shift, axis=0)))

    candidates = []
    last_error = None
    for rev, shift, src in mappings:
        M = cv2.getPerspectiveTransform(src, dst)
        warp = cv2.warpPerspective(img, M, (black_w, black_h), flags=cv2.INTER_LINEAR,
                                   borderMode=cv2.BORDER_REPLICATE)

        scale = 2.0
        radius = max(3.0, DEFAULT_GEOM['tri_h'] * scale * 0.07)
        samples = []
        for idx in range(50):
            row, col = divmod(idx, 10)
            x, y = _triangle_centroid(row, col, scale)
            x -= g['outer_white']
            y -= g['outer_white']
            samples.append(_sample_patch_rgb(warp, x, y, radius))

        refs = np.asarray(samples[46:50], dtype=float)
        sep = min(float(np.linalg.norm(refs[i]-refs[j])) for i in range(4) for j in range(i+1,4))
        if sep < 20.0:
            continue
        cells = []
        residual = 0.0
        for rgb in samples:
            dist = np.linalg.norm(refs - rgb, axis=1)
            sym = int(np.argmin(dist))
            cells.append(sym)
            residual += float(dist[sym])
        try:
            r = decode_symbols_resilient(cells, max_cell_errors=max_cell_errors)
            r['cells'] = cells
            r['photo_quad'] = [[float(x), float(y)] for x, y in src]
            r['orientation'] = {'mirrored': rev, 'quarter_turn_shift': shift}
            r['calibration_rgb'] = [[round(float(v), 1) for v in row] for row in refs]
            r['mean_colour_residual'] = residual / 50.0
            r['_warp'] = warp
            candidates.append(r)
        except Exception as e:
            last_error = e

    if not candidates:
        raise ValueError(f'frame found, but no orientation passed CRC/RS validation; last error: {last_error}')
    candidates.sort(key=lambda r: (len(r.get('corrected_cells', [])), r['mean_colour_residual']))
    best = candidates[0]
    if debug_warp:
        cv2.imwrite(str(debug_warp), best['_warp'])
    best.pop('_warp', None)
    return best



def cells_to_legacy_tag(cells: list[int]) -> str:
    """Export a 5x10 colour tag in the legacy Microsoft .tag renderer text format.

    Legacy .tag readers use: first hex nibble = colour flag (non-zero), second
    nibble = row count, followed by two 2-bit colour indices per hex nibble.
    For a 5x10 colour tag this is 2 + 25 = 27 hexadecimal characters.
    """
    if len(cells) != 50:
        raise ValueError('need exactly 50 cells')
    if any(c not in (0, 1, 2, 3) for c in cells):
        raise ValueError('colour cells must be integers 0..3')
    payload = ''.join(f'{((cells[i] << 2) | cells[i+1]):X}' for i in range(0, 50, 2))
    return '15' + payload


def legacy_tag_to_cells(text: str) -> list[int]:
    """Parse the compact legacy .tag renderer text form into colour cells."""
    compact = ''.join(text.split()).upper()
    if len(compact) < 3 or not re.fullmatch(r'[0-9A-F]+', compact):
        raise ValueError('invalid legacy .tag hex text')
    colour_flag = int(compact[0], 16)
    rows = int(compact[1], 16)
    if colour_flag == 0:
        raise ValueError('black/white .tag files are not Microsoft Tag 4-colour HCCB')
    if rows != 5:
        raise ValueError(f'expected 5 rows for Microsoft Tag 5x10, got {rows}')
    cells: list[int] = []
    for ch in compact[2:]:
        nib = int(ch, 16)
        cells.extend([(nib >> 2) & 3, nib & 3])
    if len(cells) < 50:
        raise ValueError(f'.tag payload contains only {len(cells)} colour cells')
    return cells[:50]


def write_legacy_tag(cells: list[int], path: str | Path):
    Path(path).write_text(cells_to_legacy_tag(cells) + '\n', encoding='ascii')


def decode_legacy_tag(path: str | Path) -> dict:
    cells = legacy_tag_to_cells(Path(path).read_text(encoding='ascii', errors='strict'))
    r = decode_symbols(cells)
    r['cells'] = cells
    r['legacy_tag_hex'] = cells_to_legacy_tag(cells)
    return r

def parse_cells(text: str) -> list[int]:
    vals = [int(x) for x in re.findall(r'\d+', text)]
    return vals


def _print_result(d: dict):
    for k, v in d.items():
        if isinstance(v, bytes):
            v = v.hex()
        print(f'{k}: {v}')


def self_test(rounds=100):
    assert crc16_x25(b'123456789') == 0x906E
    assert RS_GENERATOR_VALUES == [17, 9, 6, 30, 1], RS_GENERATOR_VALUES
    assert RS_GENERATOR_LOGS == [10, 29, 19, 24, 0], RS_GENERATOR_LOGS
    # Real encoder packs 5-bit symbols MSB-first and right-pads the final byte.
    assert pack_5bit_symbols_native([23, 17, 12, 20]).hex() == 'bc5940'
    assert split_5bit_symbols_native(bytes.fromhex('bc5940'))[:4] == [23, 17, 12, 20]
    cases = [(0,0), (1,1), (12345,1234567890), (65535, 0xFFFFFFFF)]
    rng = random.Random(0x5A17)
    cases += [(rng.randrange(65536), rng.randrange(1 << 32)) for _ in range(rounds)]
    for prefix, code in cases:
        enc = encode_symbols(prefix, code)
        dec = decode_symbols(enc['cells'])
        assert dec['prefix'] == prefix and dec['code'] == code
        assert dec['crc_ok']
        assert dec['rs_parity_matches_reencode']
        assert dec['filler_ok'] and dec['calibration_ok']
        tagtxt = cells_to_legacy_tag(enc['cells'])
        assert len(tagtxt) == 27 and tagtxt.startswith('15')
        assert legacy_tag_to_cells(tagtxt) == enc['cells']
    return len(cases)


def main(argv=None):
    p = argparse.ArgumentParser(description='Microsoft Tag 5x10 HCCB encoder/offline decoder')
    sub = p.add_subparsers(dest='cmd', required=True)
    pe = sub.add_parser('encode', help='encode prefix + 32-bit code')
    pe.add_argument('prefix', type=int)
    pe.add_argument('code', type=int)
    pe.add_argument('--svg')
    pe.add_argument('--png')
    pe.add_argument('--tag', help='write legacy .tag renderer-compatible hex file')
    pe.add_argument('--png-scale', type=float, default=2.0)

    pd = sub.add_parser('decode-symbols', help='decode 50 colour indices (0..3)')
    pd.add_argument('symbols', help='comma/space separated 50 values')
    pd.add_argument('--no-crc', action='store_true')

    pt = sub.add_parser('decode-tag', help='decode a legacy .tag renderer hex file')
    pt.add_argument('tag')

    pp = sub.add_parser('decode-png', help='decode a clean PNG generated by this script')
    pp.add_argument('png')
    pp.add_argument('--scale', type=float)

    ph = sub.add_parser('decode-photo', help='decode a photographed/cropped 5x10 Microsoft Tag')
    ph.add_argument('image')
    ph.add_argument('--max-cell-errors', type=int, choices=(0,1,2), default=2)
    ph.add_argument('--debug-warp')

    ps = sub.add_parser('self-test', help='run deterministic round-trip tests')
    ps.add_argument('--rounds', type=int, default=1000)

    a = p.parse_args(argv)
    if a.cmd == 'encode':
        r = encode_symbols(a.prefix, a.code)
        _print_result(r)
        if a.svg:
            render_svg(r['cells'], a.svg)
            print(f'svg: {a.svg}')
        if a.png:
            render_png(r['cells'], a.png, a.png_scale)
            print(f'png: {a.png}')
        if a.tag:
            write_legacy_tag(r['cells'], a.tag)
            print(f'tag: {a.tag}')
    elif a.cmd == 'decode-symbols':
        r = decode_symbols(parse_cells(a.symbols), verify_crc=not a.no_crc)
        _print_result(r)
    elif a.cmd == 'decode-tag':
        r = decode_legacy_tag(a.tag)
        _print_result(r)
    elif a.cmd == 'decode-png':
        r = decode_clean_png(a.png, a.scale)
        _print_result(r)
    elif a.cmd == 'decode-photo':
        r = decode_photo(a.image, a.max_cell_errors, a.debug_warp)
        _print_result(r)
    elif a.cmd == 'self-test':
        n = self_test(a.rounds)
        print(f'OK: {n} round-trip cases')


if __name__ == '__main__':
    main()
